trigger: none 

jobs: 
- job: Build
  pool:
    vmImage: ubuntu-24.04
  variables:
  - name: DOTNET_NOLOGO
    value: true
    readonly: true
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE 
    value: true
    readonly: true
    #Override to create env variable to have control where the global packages are stored for caching: https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders
  - name: NUGET_PACKAGES
    value: '$(Pipeline.Workspace)/.nuget/packages/'
    readonly: true
  - name: DOTNET_VERSION 
    value: 9
    readonly: true
        
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '${{variables.DOTNET_VERSION}}.x'
      includePreviewVersions: false
  
  - task: Cache@2
    displayName: 'Restore cache for NuGet'
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
      path: '$(NUGET_PACKAGES)'
      cacheHitVar: 'NUGET_CACHE_RESTORED'

  - task: DotNetCoreCLI@2
    displayName: Dotnet restore '**/*.csproj'
    condition: and(succeeded(), ne(variables['NUGET_CACHE_RESTORED'], 'true'))
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      restoreArguments: '--locked-mode'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: Dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'