trigger: none

jobs: 
- job: Build
  pool:
    vmImage: windows-latest
  variables:
  - name: DOTNET_NOLOGO
    value: true
    readonly: true
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE 
    value: true
    readonly: true
    #Override to create env variable to have control where the global packages are stored for caching: https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders
  - name: NUGET_PACKAGES
    value: '$(Pipeline.Workspace)/.nuget/packages/'
    readonly: true
       
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
              # URL to the .NET release metadata
              $releasesUrl = "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json"
              
              # Fetch and parse the JSON data
              $releasesData = Invoke-RestMethod -Uri $releasesUrl -UseBasicParsing
              
              # Filter for .NET 9 releases and get the latest version
              $dotNet9 = $releasesData."releases-index" | Where-Object { $_."channel-version" -like "9.0" }
              $latestNet9Sdk = $dotNet9."latest-sdk"

              # Output the latest information about .NET 9
              Write-Output "Latest .NET 9 SDK: $latestNet9Sdk"
              Write-Host "##vso[task.setvariable variable=DOTNET_VERSION;]$latestNet9Sdk"

  - task: Cache@2
    displayName: 'Restore cache for Dotnet'
    inputs:
      key: 'nuget | "$(Agent.OS)" | "$(DOTNET_VERSION)"'
      path: '$(Agent.ToolsDirectory)/dotnet'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '$(DOTNET_VERSION)'
      includePreviewVersions: false
      verbosityRestore: 'Minimal'

  - task: DotNetCoreCLI@2
    displayName: Dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'